//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.example.adapter;

import android.content.Context;

public final class WeatherAdapter_
    extends WeatherAdapter
{

    private Context context_;

    private WeatherAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static WeatherAdapter_ getInstance_(Context context) {
        return new WeatherAdapter_(context);
    }

    private void init_() {
        weatherFinder = WeatherImp_.getInstance_(context_);
        context = context_;
        initAdapter();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
